# spring specific properties
spring:
  profiles:
    active:
    - dev    
    
# custom properties
guru:
  db: # fake db specific properties
    username: Kaushlendra
    password: K123
    url: url@Kaushlendra@K123
  jms: # fake jms specific properties
    username: JMS-Kaushlendra
    password: JMS-K123
    url: JMS-url@Kaushlendra@K123


# 3 dash means profile specific separtion
# 3 dash means for spring now we have two  .yml files
# (one is application.yml, another is application-<spring.profiles>.yml)    
---
# dev env specific custom properties
spring:
  profiles: dev
guru:
  db: # fake db specific properties
    username: dev-fromsamefile-Kaushlendra
    password: dev-fromsamefile-K123
    url: dev-fromsamefile-url@Kaushlendra@K123
  jms: # fake jms specific properties
    username: dev-fromsamefile-JMS-Kaushlendra
    password: dev-fromsamefile-JMS-K123
    url: dev-fromsamefile-JMS-url@Kaushlendra@K123